### ISSUE TITLE
Campaigns not loading in Chromium based browsers, but loading in Firefox

### ISSUE THREAD

**Issue by Balaji-Ganesh** [Balaji-Ganesh/CrowdHelp-Blockchain-based-crowdfunding-platform#27]
**Not Loading in**
In Brave
![image](https://user-images.githubusercontent.com/42509652/204947503-c3cff562-257c-461a-8231-b327ec130473.png)

In Edge
![image](https://user-images.githubusercontent.com/42509652/204947584-a958c593-aa98-4751-ae46-dd1cb04ecb5e.png)

Error:
```
Uncaught (in promise) Error: Returned values aren't valid, did it run Out of Gas? You might also see this error if you are not using the correct ABI for the contract you are retrieving data from, requesting data from a block number that does not exist, or querying a node which is not fully synced.
    at c.decodeParametersWith (index.824427be.js:2498:131450)
    at c.decodeParameters (index.824427be.js:2498:131325)
    at h._decodeMethodReturn (index.824427be.js:2498:120290)
    at v.outputFormatter (index.824427be.js:2498:126124)
    at v.formatOutput (index.824427be.js:2476:11368)
    at R (index.824427be.js:2476:19587)
    at $ (index.824427be.js:2498:3639)
    at y.run (index.824427be.js:2474:65096)
    at b (index.824427be.js:2474:64596)
```

**Loading in**
![image](https://user-images.githubusercontent.com/42509652/204947720-4de4e7b9-d8f5-460c-83e7-bb5696764f19.png)

Reason.. need to figure out.

**Comment by Vasa0410** [comment]
Campaign is not loading or showing even in Firefox

Am running it in the local host 

Will you suggest any solution to load campaign pages after creating campaign

**Comment by Balaji-Ganesh** [comment]
Could you please mention the network you've uploaded the smart contract?
i.e., whether hardhat or ganache?

and please paste the error which you are getting.
Thanks.
